#!/bin/bash

cd /

#Choose Participant
echo -en '\n'
ls ./data/BLHC/RAW_data
echo -en '\n'
echo "Which participant?"; read PARTIC

##Assign raw blip_up locations
DTIRAW=`find ./data/BLHC/RAW_data/$PARTIC/ -iname "DTI_72_DIRS_A-P_*" -not -iname "*ADC*" -not -iname "*COLFA*" -not -iname "*FA*" -not -iname "*TENSOR*" -not -iname "*TRACEW*" -print | sed 's/.*\///'`

#Delete any pre-existing nifti files in raw directory
	cd ./data/BLHC/RAW_data/$PARTIC/"$DTIRAW"
	find ./ -iname '*.nii.gz' -exec rm -i {} \;
	find ./ -iname '*.bvec' -exec rm -i {} \;
	find ./ -iname '*.bval' -exec rm -i {} \;
	cd /

##Assign raw blip_down locations
DTIRAWPA=`find ./data/BLHC/RAW_data/$PARTIC/ -iname "*P-A*" | sed 's/.*\///'`

#Delete any pre-existing nifti files in raw PA directory
	cd ./data/BLHC/RAW_data/$PARTIC/"$DTIRAWPA"
	find ./ -iname '*.nii.gz' -exec rm -i {} \;
	cd /

#Delete any pre-existing nifti files in analysis directory
	cd ./data/BLHC/dti_72_preproc
	if [ -d ./"$PARTIC" ]; then	
		cd ./$PARTIC
		find ./ -iname '*.nii.gz' -exec rm -i {} \;
		find ./ -iname '*.bvec' -exec rm -i {} \;
		find ./ -iname '*.bval' -exec rm -i {} \;
	fi
	cd /

#Create a dti analysis directory for participant
	cd ./data/BLHC/dti_72_preproc
	if [ ! -d ./"$PARTIC" ]; then
		mkdir ./"$PARTIC"
	fi
	cd /

#Convert dcm to nifti for a given participant
	cd ./data/BLHC/

	find ./RAW_data/$PARTIC/"$DTIRAW" -iname '*.IMA' -print | ../dcm2nii -g y $(xargs)

	#Navigate to raw data directory for the participant
	cd ./RAW_data/$PARTIC/"$DTIRAW"

	#Rename converted nifti file to "blip_up"
	find ./ -iname '*.nii.gz' -print | mv $(xargs) "blip_up.nii.gz"

	#Rename bvecs file to "PARTIC_bvec"
	find ./ -iname '*.bvec' -print | mv $(xargs) "$PARTIC.bvec"

	#Rename bval file to "PARTIC_bval"
	find ./ -iname '*.bval' -print | mv $(xargs) "$PARTIC.bval"

#Select the converted nifti file and move it to the participant's individual analysis folder for the task
	cp ./"blip_up.nii.gz" ../../../dti_72_preproc/$PARTIC/
	cp ./"$PARTIC".bvec ../../../dti_72_preproc/$PARTIC/
	cp ./"$PARTIC".bval ../../../dti_72_preproc/$PARTIC/

cd /

#Convert dcm to nifti for the PA reverse phase encoding for a given participant
	cd ./data/BLHC/

	find ./RAW_data/$PARTIC/"$DTIRAWPA" -iname '*.IMA' -print | ../dcm2nii -g y $(xargs)

	#Navigate to raw data directory for the participant
	cd ./RAW_data/$PARTIC/"$DTIRAWPA"

	#Rename converted nifti file to "Data1"
	find ./ -iname '*.nii.gz' -print | mv $(xargs) "blip_down.nii.gz"

	cp ./blip_down.nii.gz ../../../dti_72_preproc/$PARTIC/
	
	#Navigate to participant's directory
	cd /
	cd ./data/BLHC/dti_72_preproc/$PARTIC
	
#Check converted image in fslview while eddy correcting
	fslview blip_up.nii.gz &

#Create b0_blip_up and b0_blip_down
fslroi blip_up b0_blip_up1 0 1
fslroi blip_up b0_blip_up2 30 1
fslroi blip_down b0_blip_down1 0 1
fslmerge -t both_b0 b0_blip_up1 b0_blip_up2 b0_blip_down1

##Create parameters file to feed to TOPUP and EDDY
printf "0 -1 0 0.12032\n0 -1 0 0.12032\n0 1 0 0.12032" > parameters.txt 

#Run TOPUP
topup --imain=both_b0 --datain=parameters.txt --config=$FSLDIR/etc/flirtsch/b02b0.cnf --out=my_topup_results --iout=my_hifi_b0 --verbose

fslmaths my_hifi_b0 -Tmean my_hifi_b0
bet my_hifi_b0 my_hifi_b0_brain -m

#Create index file
indx=""
for ((i=1; i<=37; i+=1)); do indx="$indx 1"; done
for ((i=1; i<=37; i+=1)); do indx="$indx 2"; done
echo $indx > index1.txt

#EDDY
eddy --imain=blip_up --mask=my_hifi_b0_brain_mask --acqp=parameters.txt --index=index1.txt --bvecs="$PARTIC.bvec" --bvals="$PARTIC.bval" --topup=my_topup_results --out=eddy_corrected_data

#Brain extraction
	bet2 eddy_corrected_data.nii.gz "$PARTIC.bet" -m -f 0.3

#DTIFIT
	dtifit -k eddy_corrected_data.nii.gz -o "$PARTIC" -m "$PARTIC.bet" -r "$PARTIC.bvec" -b "$PARTIC.bval"

