#!/bin/bash

#Welcome
echo -en '\n'
echo "Welcome to CONVERTIT. This simple UNIX script will quickly convert dcm images"
echo "to nifti, move and rename those nifti images to their respective individual"
echo "analysis directory, and prepare them for analysis in SPM. This version will" 
echo "populate all images (BOLD and anatomical) for all tasks for a given participant."
echo "Type cntrl+c at any time to stop the script."
echo -en '\n'

cd ../..

#Choose study
echo -en '\n'
ls ./data/
echo -en '\n'
echo "Which study?"; read STUDY

#Choose Participant
echo -en '\n'
ls ./data/$STUDY/RAW_data
echo -en '\n'
echo "Which participant?"; read PARTIC

#Create Participant's individual analysis directory from template "x"
cd ./data/$STUDY/indiv_analysis/
cp -R ./x ./$PARTIC
cd 
cd ../..

#Choose visit
echo -en '\n'
ls ./data/$STUDY/indiv_analysis/$PARTIC/bold/rest
echo -en '\n'
echo "Which visit?"; read VISIT

#Anatomical
	#Delete any pre-existing nifti files in directory
	cd ./data/$STUDY/RAW_data/$PARTIC/T1_MPRAGE_1MM_0002/
	find ./ -iname '*.nii' | xargs rm -f
	cd
	cd ../..

	#Delete any pre-existing nifti files in individual analysis directory
	cd ./data/$STUDY/indiv_analysis/$PARTIC/3danat_MSIT/"$VISIT"/
	find ./ -iname '*.nii' | xargs rm -f
	cd
	cd ../..

	#Convert dcm to nifti for a given participant and BOLD task
	find ./data/$STUDY/RAW_data/$PARTIC/T1_MPRAGE_1MM_0002/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

	#Navigate to raw data directory for the participant's task
	cd ./data/$STUDY/RAW_data/$PARTIC/T1_MPRAGE_1MM_0002/

	#Select the converted nifti file and move it to the participant's individual analysis folder for the task
	find ./ -not -iname "co*" -not -iname "o*" -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/3danat_MSIT/"$VISIT"/

	#Navigate to the nifiti file in the participant's BOLD directory for the task.
	cd ../../../indiv_analysis/$PARTIC/3danat_MSIT/"$VISIT"/

	#Rename converted nifti file
	find ./ -iname '*.nii' -print | mv $(xargs) "$PARTIC"_Anatomical.nii
	
	#Copy to other anatomical task folders
	find ./ -iname '*.nii' -print | xargs cp -t ../../3danat_NBACK/"$VISIT"/
	find ./ -iname '*.nii' -print | xargs cp -t ../../3danat_rest/"$VISIT"/

	#Return to root directory
	cd ../../../../../../

	#BOLD Tasks and Resting
	if [ $VISIT = "Baseline" ]
	then
		#NBACK BOLD Baseline
		#Delete any pre-existing nifti files in RAW data directory
		cd ./data/$STUDY/RAW_data/$PARTIC/NBACK_0007/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..
		
		#Delete any pre-existing nifti files in individual analysis directory
		cd ./data/$STUDY/indiv_analysis/$PARTIC/bold/NBACK_Bas/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Convert dcm to nifti for a given participant and BOLD task
		find ./data/$STUDY/RAW_data/$PARTIC/NBACK_0007/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

		#Navigate to raw data directory for the participant's task
		cd ./data/$STUDY/RAW_data/$PARTIC/NBACK_0007/

		#Select the converted nifti file and move it to the participant's individual analysis folder for the task
		find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/NBACK_Bas/

		#Navigate to the nifiti file in the participant's BOLD directory for the task.
		cd ../../../indiv_analysis/$PARTIC/bold/NBACK_Bas/

		#Rename converted nifti file
		find ./ -iname '*.nii' -print | mv $(xargs) NBACK_Bas_RAW_"$PARTIC".nii

		#Return to root directory
		cd ../../../../../../

		#MSIT BOLD Baseline
		#Delete any pre-existing nifti files in directory
		cd ./data/$STUDY/RAW_data/$PARTIC/MSIT_0005/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Delete any pre-existing nifti files in individual analysis directory
		cd ./data/$STUDY/indiv_analysis/$PARTIC/bold/MSIT_Bas/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Convert dcm to nifti for a given participant and BOLD task
		find ./data/$STUDY/RAW_data/$PARTIC/MSIT_0005/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

		#Navigate to raw data directory for the participant's task
		cd ./data/$STUDY/RAW_data/$PARTIC/MSIT_0005/

		#Select the converted nifti file and move it to the participant's individual analysis folder for the task
		find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/MSIT_Bas/

		#Navigate to the nifiti file in the participant's BOLD directory for the task.
		cd ../../../indiv_analysis/$PARTIC/bold/MSIT_Bas/

		#Rename converted nifti file
		find ./ -iname '*.nii' -print | mv $(xargs) MSIT_Bas_RAW_"$PARTIC".nii

		#Return to root directory
		cd ../../../../../../
		
		#Resting BOLD Baseline
		#Delete any pre-existing nifti files in directory
		cd ./data/$STUDY/RAW_data/$PARTIC/resting/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Delete any pre-existing nifti files in individual analysis directory
		cd ./data/$STUDY/indiv_analysis/$PARTIC/bold/rest_Bas/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Convert dcm to nifti for a given participant and BOLD task
		find ./data/$STUDY/RAW_data/$PARTIC/resting/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

		#Navigate to raw data directory for the participant's task
		cd ./data/$STUDY/RAW_data/$PARTIC/resting/

		#Select the converted nifti file and move it to the participant's individual analysis folder for the task
		find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/rest_Bas/

		#Navigate to the nifiti file in the participant's BOLD directory for the task.
		cd ../../../indiv_analysis/$PARTIC/bold/rest_Bas/

		#Rename converted nifti file
		find ./ -iname '*.nii' -print | mv $(xargs) rest_Bas_RAW_"$PARTIC".nii

		#Return to root directory
		cd ../../../../../../
	fi

	if [ $VISIT = "PostTX" ]
	then
		#NBACK BOLD Post-TX
		#Delete any pre-existing nifti files in directory
		cd ./data/$STUDY/RAW_data/$PARTIC/NBACK_0007/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Delete any pre-existing nifti files in individual analysis directory
		cd ./data/$STUDY/indiv_analysis/$PARTIC/bold/NBACK_PostTX/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Convert dcm to nifti for a given participant and BOLD task
		find ./data/$STUDY/RAW_data/$PARTIC/NBACK_0007/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

		#Navigate to raw data directory for the participant's task
		cd ./data/$STUDY/RAW_data/$PARTIC/NBACK_0007/

		#Select the converted nifti file and move it to the participant's individual analysis folder for the task
		find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/NBACK_PostTX/

		#Navigate to the nifiti file in the participant's BOLD directory for the task.
		cd ../../../indiv_analysis/$PARTIC/bold/NBACK_PostTX/

		#Rename converted nifti file
		find ./ -iname '*.nii' -print | mv $(xargs) NBACK_PostTX_"$PARTIC".nii

		#Return to root directory
		cd ../../../../../../

		#NBACK BOLD Post-TX
		#Delete any pre-existing nifti files in directory
		cd ./data/$STUDY/RAW_data/$PARTIC/MSIT_0005/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Delete any pre-existing nifti files in individual analysis directory
		cd ./data/$STUDY/indiv_analysis/$PARTIC/bold/MSIT_PostTX/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Convert dcm to nifti for a given participant and BOLD task
		find ./data/$STUDY/RAW_data/$PARTIC/MSIT_0005/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

		#Navigate to raw data directory for the participant's task
		cd ./data/$STUDY/RAW_data/$PARTIC/MSIT_0005/

		#Select the converted nifti file and move it to the participant's individual analysis folder for the task
		find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/MSIT_PostTX/

		#Navigate to the nifiti file in the participant's BOLD directory for the task.
		cd ../../../indiv_analysis/$PARTIC/bold/MSIT_PostTX/

		#Rename converted nifti file
		find ./ -iname '*.nii' -print | mv $(xargs) MSIT_PostTX_"$PARTIC".nii

		#Return to root directory
		cd ../../../../../../
		
		#Resting BOLD Post-Tx
		#Delete any pre-existing nifti files in directory
		cd ./data/$STUDY/RAW_data/$PARTIC/resting/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Delete any pre-existing nifti files in individual analysis directory
		cd ./data/$STUDY/indiv_analysis/$PARTIC/bold/rest_PostTX/
		find ./ -iname '*.nii' | xargs rm -f
		cd
		cd ../..

		#Convert dcm to nifti for a given participant and BOLD task
		find ./data/$STUDY/RAW_data/$PARTIC/resting/ -iname '*.dcm' -print | ./home/scanlab/dcm2nii $(xargs)

		#Navigate to raw data directory for the participant's task
		cd ./data/$STUDY/RAW_data/$PARTIC/resting/

		#Select the converted nifti file and move it to the participant's individual analysis folder for the task
		find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/rest_PostTX/

		#Navigate to the nifiti file in the participant's BOLD directory for the task.
		cd ../../../indiv_analysis/$PARTIC/bold/rest_PostTX/

		#Rename converted nifti file
		find ./ -iname '*.nii' -print | mv $(xargs) rest_PostTX_"$PARTIC".nii

		#Return to root directory
		cd ../../../../../../
	fi

