#!/bin/bash

#Welcome
echo -en '\n'
echo "Welcome to CONVERTIT. This simple UNIX script will quickly convert dcm images to nifti, move and rename those nifti images to their respective individual analysis directory, and prepare them for analysis in SPM."
echo -en '\n'

#bold or anatomical
echo "Is this the anatomical image? (if yes, type "1"; if no, type "0")"; read TYPE

if [ $TYPE = 1 ] 
then
	cd ../../

	#choose study
	echo -en '\n'
	ls ./data/
	echo -en '\n'
	echo "Which study?"; read STUDY

	#choose Participant
	echo -en '\n'
	ls ./data/$STUDY/RAW_data
	echo -en '\n'
	echo "Which participant?"; read PARTIC

	#Choose task of interest
	echo -en '\n'
	ls ./data/$STUDY/RAW_data/$PARTIC/
	echo -en '\n'
	echo "Location of anatomical image (i.e. T1 image)?"; read ANAT

	#Choose Source of anatomical image
	echo -en '\n'
	ls ./data/$STUDY/indiv_analysis/$PARTIC/
	echo -en '\n'
	echo "Which task?"; read TASK

	#Choose Destination Anatomical Visit Directory
	echo -en '\n'
	ls ./data/$STUDY/indiv_analysis/$PARTIC/$TASK
	echo -en '\n'
	echo "Which visit?"; read VISIT

	#Convert dcm to nifti for a given participant and BOLD task
	find ./data/$STUDY/RAW_data/$PARTIC/"$ANAT"/ -iname '*.dcm' -print | ./data/dcm2nii $(xargs)

	#Navigate to raw data directory for the participant's task
	cd ./data/$STUDY/RAW_data/$PARTIC/"$ANAT"/

	#Select the converted nifti file and move it to the participant's individual analysis folder for the task
	find ./ -not -iname "co*" -not -iname "o*" -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/"$TASK"/"$VISIT"/

	#Navigate to the nifiti file in the participant's BOLD directory for the task.
	cd ../../../indiv_analysis/$PARTIC/"$TASK"/"$VISIT"/

	#rename converted nifti file
	find ./ -iname '*.nii' -print | mv $(xargs) "'$PARTIC'_Anatomical.nii"

	#return to root directory
	cd ../../../../

else
	cd ../../

	#choose study
	echo -en '\n'
	ls ./data/
	echo -en '\n'
	echo "Which study?"; read STUDY

	#choose Participant
	echo -en '\n'
	ls ./data/$STUDY/RAW_data
	echo -en '\n'
	echo "Which participant?"; read PARTIC

	#Choose task of interest
	echo -en '\n'
	ls ./data/$STUDY/RAW_data/$PARTIC
	echo -en '\n'
	echo "Which task?"; read TASK

	#Choose Destination Bold Directory
	echo -en '\n'
	ls ./data/$STUDY/indiv_analysis/$PARTIC/bold/
	echo -en '\n'
	echo "Which destination folder?"; read DEST

	#Convert dcm to nifti for a given participant and BOLD task
	find ./data/$STUDY/RAW_data/$PARTIC/"$TASK"/ -iname '*.dcm' -print | ./data/dcm2nii $(xargs)

	#Navigate to raw data directory for the participant's task
	cd ./data/$STUDY/RAW_data/$PARTIC/"$TASK"/

	#Select the converted nifti file and move it to the participant's individual analysis folder for the task
	find ./ -iname '*.nii' | xargs cp -t ../../../indiv_analysis/$PARTIC/bold/"$DEST"/

	#Navigate to the nifiti file in the participant's BOLD directory for the task.
	cd ../../../indiv_analysis/$PARTIC/bold/"$DEST"/

	#rename converted nifti file
	find ./ -iname '*.nii' -print | mv $(xargs) "'$TASK'_raw_$PARTIC.nii"

	#return to root directory
	cd ../../../../	
fi
