#!/bin/bash

for d in /data2/tbimodel/dti_denoised/*; do
	PARTIC=`echo $d | sed 's/.*\///'`

	cd /data2/tbimodel/dti_denoised/"$PARTIC"
	
	dcm2nii -g n -m n Data1_eddy.nii.gz	

	matlab -nodesktop -nosplash -r "addpath(genpath('/usr/local/LPCA Denoising Software')); addpath(genpath('/usr/local/nifti_analyzer')); Run_LPCA('fData1_eddy.nii', 'Data1.bval'); clear; quit;"
	dcm2nii -g y -m n fData1_eddy_denoised.nii

	mv ffData1_eddy_denoised.nii.gz eddy_corrected_data_denoised.nii.gz

	bet eddy_corrected_data_denoised.nii.gz bet.nii.gz -m -f 0.3

	rm -f *_L1.nii.gz
	rm -f *_L2.nii.gz
	rm -f *_L3.nii.gz
	rm -f *_MD.nii.gz
	rm -f *_MO.nii.gz
	rm -f *_S0.nii.gz
	rm -f *_V1.nii.gz
	rm -f *_V2.nii.gz
	rm -f *_V3.nii.gz
	rm -f FA_*
	
	#DTIFIT
	dtifit -k eddy_corrected_data_denoised.nii.gz -o "$PARTIC" -m bet_mask.nii.gz -r Data1_rotated_bvec.bvec -b Data1.bval

cd /

done

