#!/bin/bash

for d in /data/BLHC/dti_denoised/*; do
	PARTIC=`echo $d | sed 's/.*\///'`

	DTIRAW=`find /data/BLHC/RAW_data/$PARTIC/ -iname "DTI_72_DIRS_A-P_*" -not -iname "*ADC*" -not -iname "*COLFA*" -not -iname "*FA*" -not -iname "*TENSOR*" -not -iname "*TRACEW*" -print | sed 's/.*\///'`

	if [[ -z "$DTIRAW" ]]; then
		exit
	fi
		

	#Create a dti analysis directory for participant
	cd /data/BLHC/dti_denoised_FINAL
	if [ ! -d ./"$PARTIC" ]; then
		mkdir ./"$PARTIC"
	fi
	cd
	cd /

	#Convert dcm to nifti for a given participant
	cd /data/BLHC/

	find ./RAW_data/$PARTIC/$DTIRAW -iname '*.IMA' -print | ../dcm2nii -g y $(xargs)

	#Navigate to raw data directory for the participant
	cd ./RAW_data/$PARTIC/$DTIRAW

	#Rename converted nifti file to "Data1"
	find ./ -iname '*.nii.gz' -print | mv $(xargs) 'Data1.nii.gz'

	#Rename bvecs file to "Data1_bvec"
	find ./ -iname '*.bvec' -print | mv $(xargs) 'Data1.bvec'

	#Rename bval file to "Data1_bval"
	find ./ -iname '*.bval' -print | mv $(xargs) 'Data1.bval'

	#Select the converted nifti file and move it to the participant's individual analysis folder for the task
	cp ./Data1.nii.gz /data/BLHC/dti_denoised_FINAL/$PARTIC/
	cp ./Data1.bvec /data/BLHC/dti_denoised_FINAL/$PARTIC/
	cp ./Data1.bval /data/BLHC/dti_denoised_FINAL/$PARTIC/
	
	#Navigate to participant's directory
	cd /data/BLHC/dti_denoised_FINAL/$PARTIC

	#Eddy correct
	eddy_correct Data1.nii.gz Data1_eddy 0

	#Rotate bvecs
	fdt_rotate_bvecs Data1.bvec Data1_rotated_bvec.bvec Data1_eddy.ecclog
	
	dcm2nii -g n -m n Data1_eddy.nii.gz

	matlab -nodesktop -nosplash -r "addpath(genpath('/usr/local/LPCA Denoising Software')); addpath(genpath('/usr/local/nifti_analyzer')); Run_LPCA('fData1_eddy.nii','Data1.bval'); clear; quit;"

	dcm2nii -g y -m n fData1_eddy_denoised.nii

	mv ffData1_eddy_denoised.nii.gz eddy_corrected_data_denoised.nii.gz

	bet eddy_corrected_data_denoised.nii.gz bet.nii.gz -m -f 0.3
	
	#DTIFIT
	dtifit -k eddy_corrected_data_denoised.nii.gz -o "$PARTIC" -m bet_mask.nii.gz -r Data1_rotated_bvec.bvec -b Data1.bval

cd /

done

