#!/bin/bash
#delimdb
#Created by Matt Allbright
#Takes delimited text files and formats them into an easy to use delimited file

#Navigate to directory
#Currently, this is just TRACULA
cd /mnt/data1/TBIMODEL/TRACULA/tractography_output/

#Remove previous database file
if [ -e database ]; then
  echo "Removing old database file."
  echo -en '\n'
  rm -rf database
fi

#Creates an array of all usernames
arr=( * )

#Create new file
echo "Creating new database file."
touch database

#Add all the top values
echo -e "FA.fminor \t MD.fminor \t FA.lh.atr \t MD.lh.atr \t FA.lh.cab \t MD.lh.cab \t FA.lh.ccg \t MD.lh.ccg \t FA.lh.cst \t MD.lh.cst \t FA.lh.ilf \t MD.lh.ilf \t FA.lh.slfp \t MD.lh.slfp \t FA.lh.slft \t MD.lh.slft \t FA.lh.unc \t  MD.lh.unc \t  FA.rh.atr \t  MD.rh.atr \t  FA.rh.cab \t  MD.rh.cab \t  FA.rh.ccg \t  MD.rh.ccg \t  FA.rh.cst \t  MD.rh.cst \t  FA.rh.ilf \t  MD.rh.ilf \t  FA.rh.slfp \t MD.rh.slfp \t FA.rh.slft \t MD.rh.slft \t FA.rh.unc \t  MD.rh.unc" >> database

#For each value in array, read second line and add to darabase file
for i in "${arr[@]}"; do
  echo -en '\n'
  echo "Creating line for "$i"..."
  echo -e "$i \t" | sed -n '2{p;q;}' /mnt/data1/TBIMODEL/TRACULA/tractography_output/"$i"/stats/ALLTRACTS_"$i" >> database
  echo -en '\n'
  echo "Line created."
done

echo -en '\n'
echo "All complete."
