#!/bin/bash
#delimdb
#Created by Matt Allbright
#Takes delimited text files and formats them into an easy to use delimited file

#Navigate to directory
#Currently, this is just TRACULA
cd /mnt/data1/TBIMODEL/TRACULA/tractography_output/

#Remove previous database file
if [ -e database ]; then
  echo "Removing old database file."
  echo -en '\n'
  rm -rf database
fi

#Creates an array of all usernames
arr=( * )

#Create new file
echo "Creating new database file."
touch database

#Add all the top values
echo -e "Partic\tFA.fminor\tMD.fminor\tFA.lh.atr\tMD.lh.atr\tFA.lh.cab\tMD.lh.cab\tFA.lh.ccg\tMD.lh.ccg\tFA.lh.cst\tMD.lh.cst\tFA.lh.ilf\tMD.lh.ilf\tFA.lh.slfp\tMD.lh.slfp\tFA.lh.slft\tMD.lh.slft\tFA.lh.unc\t MD.lh.unc\t FA.rh.atr\t MD.rh.atr\t FA.rh.cab\t MD.rh.cab\t FA.rh.ccg\t MD.rh.ccg\t FA.rh.cst\t MD.rh.cst\t FA.rh.ilf\t MD.rh.ilf\t FA.rh.slfp\tMD.rh.slfp\tFA.rh.slft\tMD.rh.slft\tFA.rh.unc\t MD.rh.unc" >> database

#For each value in array, read second line and add to darabase file
for i in "${arr[@]}"; do
  echo -en '\n'
  echo "Creating line for "$i"..."
  sed -e 's/^/\t/' -e 's/^/'"${i}"'/' -e '2{p;q;}' /mnt/data1/TBIMODEL/TRACULA/tractography_output/"$i"/stats/ALLTRACTS_"$i" >> database
  echo -en '\n'
  echo "Line created."
done

echo -en '\n'
echo "All complete."
