#!/bin/bash
#delimdb
#Created by Matt Allbright
#Takes delimited text files and formats them into an easy to use delimited file

#Navigate to directory
#Currently, this is just TRACULA
cd /mnt/data1/TBIMODEL/TRACULA/tractography_output/

#Remove previous database file
if [ -e database ]; then
  echo "Removing old database file."
  echo -en '\n'
  rm -rf database
fi

#Creates an array of all usernames
arr=( * )

#Create new file
echo "Creating new database file."
touch database

#Add all the top values
echo -e "Partic\n\tFA.fminor\n\tMD.fminor\n\tFA.lh.atr\n\tMD.lh.atr\n\tFA.lh.cab\n\tMD.lh.cab\n\tFA.lh.ccg\n\tMD.lh.ccg\n\tFA.lh.cst\n\tMD.lh.cst\n\tFA.lh.ilf\n\tMD.lh.ilf\n\tFA.lh.slfp\n\tMD.lh.slfp\n\tFA.lh.slft\n\tMD.lh.slft\n\tFA.lh.unc\n\t MD.lh.unc\n\t FA.rh.atr\n\t MD.rh.atr\n\t FA.rh.cab\n\t MD.rh.cab\n\t FA.rh.ccg\n\t MD.rh.ccg\n\t FA.rh.cst\n\t MD.rh.cst\n\t FA.rh.ilf\n\t MD.rh.ilf\n\t FA.rh.slfp\n\tMD.rh.slfp\n\tFA.rh.slft\n\tMD.rh.slft\n\tFA.rh.unc\n\t MD.rh.unc" >> database

#For each value in array, read second line and add to darabase file
for i in "${arr[@]}"; do
  echo -en '\n'
  echo "Creating line for "$i"..."
  echo -e ""$i"\n\t" | sed -n 's/$/2{p;q;}/' /mnt/data1/TBIMODEL/TRACULA/tractography_output/"$i"/stats/ALLTRACTS_"$i" >> database
  echo -en '\n'
  echo "Line created."
done

echo -en '\n'
echo "All complete."
